export const TYPES = {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    CREATE_STREAM: 'CREATE_STREAM',
    FETCH_STREAM: 'FETCH_STREAM',
    FETCH_STREAMS: 'FETCH_STREAMS',
    DELETE_STREAM: 'DELETE_STREAM',
    UPDATE_STREAM: 'UPDATE_STREAM'
};